web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name="index"),
    path('about',views.about,name="about"),
    path('services',views.services,name="services"),
    path('packages',views.packages,name="packages"),
    path('blog',views.blog,name="blog"),
    path('gallery',views.gallery,name="gallery"),
    path('gallery-single/<int:id>/',views.gallery_single,name="gallery_single"),
    path('contact',views.contact,name="contact"),
    path('service-details/<int:id>/',views.service_details,name="service_details"),
    path('blog-details/<int:id>/',views.blog_details,name="blog_details"),
    path('package-details/<int:id>/',views.package_details,name="package_details")
]

zonholidays/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models
from versatileimagefield.fields import VersatileImageField

# Create your models here.

class Blog(models.Model):
    blog_type = models.CharField(max_length=100)
    blog_image = VersatileImageField('Blog Image',upload_to = 'image/testimagemodel/')
    blogger_name = models.CharField(max_length=100)
    blog_date = models.DateField()
    blog_title = models.CharField(max_length=200)
    blog_content = models.TextField()

    def __str__(self):
        return str(self.blogger_name)

class Place(models.Model):
    place_name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.place_name)

class Gallery(models.Model):
    image = VersatileImageField('Image',upload_to = 'image/testimagemodel/')
    place = models.ForeignKey(Place,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return str(self.place)

class Service(models.Model):
    service_image = VersatileImageField('Image',upload_to = 'image/testimagemodel/')
    service_name = models.CharField(max_length=100)
    service_details = models.TextField()

    def __str__(self):
        return str(self.service_name)

class Testimonial(models.Model):
    image = VersatileImageField('Image',upload_to = 'image/testimagemodel/')
    review = models.TextField()
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)

class TourType(models.Model):
    type = models.CharField(max_length=100)

    def __str__(self):
        return str(self.type)

class Package(models.Model):
    place_name = models.CharField(max_length = 100)
    tour_type = models.ForeignKey(TourType,on_delete=models.CASCADE,null=True)
    package_details = models.TextField()
    image_1 = VersatileImageField('Image1',upload_to = 'image/testimagemodel/')
    image_2 = VersatileImageField('Image2',upload_to = 'image/testimagemodel/')
    image_3 = VersatileImageField('Image3',upload_to = 'image/testimagemodel/')
    image_4 = VersatileImageField('Image4',upload_to = 'image/testimagemodel/')
    image_5 = VersatileImageField('Image5',upload_to = 'image/testimagemodel/')
    image_6 = VersatileImageField('Image6',upload_to = 'image/testimagemodel/')
    total_days = models.CharField(max_length = 100)
    group_size = models.CharField(max_length=100)
    number_of_days = models.IntegerField()
    number_of_nights = models.IntegerField()
    rate = models.CharField(max_length=100)

    def __str__(self):
        return str(self.place_name)

web/views.py
from django.shortcuts import render
from web.models import Testimonial, Blog, Service, Gallery, Place, Package, TourType

# Create your views here.

def index(request):
    testimonials = Testimonial.objects.filter().all()[:3]
    gallery = Gallery.objects.filter().all()[:6]
    package = Package.objects.filter().all()[:6]
    tour_type = TourType.objects.filter().all()
    place = Place.objects.filter().all()
    domestic_packages = Package.objects.filter(tour_type=1)
    international_packages = Package.objects.filter(tour_type=2)
    hajj_packages = Package.objects.filter(tour_type=3)  
    context = {
        'testimonials' : testimonials,
        'gallery' : gallery,
        'packages' : package,
        'tour_type' : tour_type,
        'place' : place,
        'domestic_packages' : domestic_packages,
        'international_packages' : international_packages,
        'hajj_packages' : hajj_packages
    }
    return render(request,'web/index.html',context)

def about(request):
    testimonials = Testimonial.objects.filter().all()[:3]
    context = {
        'testimonials' : testimonials,
    }
    return render(request,'web/about.html',context)

def services(request):
    services = Service.objects.filter().all()
    context = {
        'services' : services
    }
    return render(request,'web/services.html',context)

def packages(request):
    packages = Package.objects.filter().all()
    tour_type = TourType.objects.filter().all()
    domestic_packages = Package.objects.filter(tour_type=1)
    international_packages = Package.objects.filter(tour_type=2)
    hajj_packages = Package.objects.filter(tour_type=3)
    context = {
        'packages' : packages,
        'tour_type' : tour_type,
        'domestic_packages' : domestic_packages,
        'international_packages' : international_packages,
        'hajj_packages' : hajj_packages
    }
    return render(request,'web/packages.html',context)

def blog(request):
    blogs = Blog.objects.filter().all()
    context = {
        'blogs' : blogs
    }
    return render(request,'web/blog.html',context)

# def guide(request):
#     guides = Guide.objects.filter().all()
#     context = {
#         'guides' : guides
#     }
#     return render(request,'web/guide.html',context)

def gallery(request):
    gallery = Gallery.objects.filter().all()
    context = {
        'gallery' : gallery
    }
    return render(request,'web/gallery.html',context)

def contact(request):
    return render(request,'web/contact.html')

def service_details(request,id):
    service_details = Service.objects.get(id=id)
    context = {
        'service_details' : service_details
    }
    return render(request,'web/service-details.html',context)

def blog_details(request,id):
    blog = Blog.objects.get(id=id)
    context = {
        'blog' : blog
    }
    return render(request,'web/blog-details.html',context)

def package_details(request,id):
    package_details = Package.objects.get(id=id)
    context = {
        'package_details' : package_details
    }
    return render(request,'web/package-details.html',context)

def gallery_single(request,id):
    place = Place.objects.get(id=id)
    images = Gallery.objects.filter(place = place.id)
    print(place)
    context = {
        'images' : images,
        'place' : place
    }
    return render(request,'web/gallery-single.html',context)

templates/web/blog.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}


<div class="breadcrumb breadcrumb-style-one">
    <div class="container">
        <div class="col-lg-12 text-center">
            <h2 class="breadcrumb-title">Blog</h2>
            <ul class="d-flex justify-content-center breadcrumb-items">
                <li class="breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                <li class="breadcrumb-item active">Blog</li>
            </ul>
        </div>
    </div>
</div>

<div class="blog-wrapper pt-80">
    <div class="container">
        <div class="row">
            {% for blog in blogs %}
            <div class="col-lg-4 col-md-6">
                <div class="blog-card-gamma">
                    <div class="blog-thumb">
                        <a href="{% url 'web:blog_details' blog.id %}">
                            <img src="{{blog.blog_image.url}}" alt="">
                        </a>
                        <div class="blog-lavel">
                            <a href="{% url 'web:blog_details' blog.id %}">{{blog.blog_type}}</a>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-body-top">
                            <a href="{% url 'web:blog_details' blog.id %}" class="blog-writer"><i class="bi bi-person-circle"></i> By {{blog.blogger_name}} </a>
                            <a href="{% url 'web:blog_details' blog.id %}" class="blog-comments"><i class="bi bi-calendar3"></i> {{blog.blog_date}}</a>
                        </div>
                        <h4 class="blog-title"><a href="{% url 'web:blog_details' blog.id %}">{{blog.blog_title}}</a></h4>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/web/packages.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}


<div class="breadcrumb breadcrumb-style-one">
    <div class="container">
        <div class="col-lg-12 text-center">
            <h2 class="breadcrumb-title">Packages</h2>
            <ul class="d-flex justify-content-center breadcrumb-items">
                <li class="breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                <li class="breadcrumb-item active">Packages</li>
            </ul>
        </div>
    </div>
</div>

<div class="package-area offer-package-style-one pt-110 pb-110">
    <div class="container">
        <div class="row align-items-center">
            <div class="offer-switch-button2">
                <ul class="nav nav-pills mb-3 justify-content-center gap-sm-4 gap-3" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="pills-offer0" data-bs-toggle="pill"
                            data-bs-target="#pills-offer-tab0" type="button" role="tab" aria-controls="pills-offer-tab0"
                            aria-selected="true">All</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-offer1" data-bs-toggle="pill"
                            data-bs-target="#pills-offer-tab1" type="button" role="tab" aria-controls="pills-offer-tab1"
                            aria-selected="true">Domestic</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-offer2" data-bs-toggle="pill"
                            data-bs-target="#pills-offer-tab2" type="button" role="tab" aria-controls="pills-offer-tab2"
                            aria-selected="false">International</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-offer3" data-bs-toggle="pill"
                            data-bs-target="#pills-offer-tab3" type="button" role="tab" aria-controls="pills-offer-tab3"
                            aria-selected="false">Hajj & Umrah</button>
                    </li>
                </ul>
            </div>
            <div class="offer-single-tabs">
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-offer-tab0" role="tabpanel"
                        aria-labelledby="pills-offer0">
                        <div class="row d-flex justify-content-center g-4">
                            {% for packages in packages %}
                            <div class="col-lg-4 col-md-6 col-6 fadeffect">
                                <div class="package-card-beta">
                                    <div class="package-thumb">
                                        <a href="{% url 'web:package_details' packages.id %}"><img
                                                src="{{packages.image_1.url}}" alt=""></a>
                                        <p class="card-lavel">
                                            <i class="bi bi-clock"></i> <span>{{packages.number_of_days}} Day & {{packages.number_of_nights}} night</span>
                                        </p>
                                    </div>
                                    <div class="package-card-body">
                                        <h3 class="p-card-title"><a href="{% url 'web:package_details' packages.id %}">{{packages.place_name}}</a></h3>
                                        <div class="p-card-bottom">
                                            <div class="book-btn">
                                                <a href="{% url 'web:package_details' packages.id %}">Book Now <i
                                                        class='bx bxs-right-arrow-alt'></i></a>
                                            </div>
                                            <div class="p-card-info">
                                                <span>From</span>
                                                <h6>₹{{packages.rate}} <span>Per Person</span></h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="package-page-btn text-center mt-60">
                            <a href="{% url 'web:packages' %}" class="button-fill-round">View All Packages</a>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-offer-tab1" role="tabpanel"
                        aria-labelledby="pills-offer1">
                        <div class="row d-flex justify-content-center g-4">
                            {% for packages in domestic_packages %}
                            <div class="col-lg-4 col-md-6 col-6 fadeffect">
                                <div class="package-card-beta">
                                    <div class="package-thumb">
                                        <a href="{% url 'web:package_details' packages.id %}"><img
                                                src="{{packages.image_1.url}}" alt=""></a>
                                        <p class="card-lavel">
                                            <i class="bi bi-clock"></i> <span>{{packages.number_of_days}} Day & {{packages.number_of_nights}} night</span>
                                        </p>
                                    </div>
                                    <div class="package-card-body">
                                        <h3 class="p-card-title"><a href="{% url 'web:package_details' packages.id %}">{{packages.place_name}}</a></h3>
                                        <div class="p-card-bottom">
                                            <div class="book-btn">
                                                <a href="{% url 'web:package_details' packages.id %}">Book Now <i
                                                        class='bx bxs-right-arrow-alt'></i></a>
                                            </div>
                                            <div class="p-card-info">
                                                <span>From</span>
                                                <h6>₹{{packages.rate}} <span>Per Person</span></h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="package-page-btn text-center mt-60">
                            <a href="{% url 'web:packages' %}" class="button-fill-round">View All Packages</a>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-offer-tab2" role="tabpanel" aria-labelledby="pills-offer2">
                        <div class="row d-flex justify-content-center g-4">
                            {% for packages in international_packages %}
                            <div class="col-lg-4 col-md-6 col-6 fadeffect">
                                <div class="package-card-beta">
                                    <div class="package-thumb">
                                        <a href="{% url 'web:package_details' packages.id %}"><img
                                                src="{{packages.image_1.url}}" alt=""></a>
                                        <p class="card-lavel">
                                            <i class="bi bi-clock"></i> <span>{{packages.number_of_days}} Day & {{packages.number_of_nights}} night</span>
                                        </p>
                                    </div>
                                    <div class="package-card-body">
                                        <h3 class="p-card-title"><a href="{% url 'web:package_details' packages.id %}">{{packages.place_name}}</a></h3>
                                        <div class="p-card-bottom">
                                            <div class="book-btn">
                                                <a href="{% url 'web:package_details' packages.id %}">Book Now <i
                                                        class='bx bxs-right-arrow-alt'></i></a>
                                            </div>
                                            <div class="p-card-info">
                                                <span>From</span>
                                                <h6>₹{{packages.rate}} <span>Per Person</span></h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="package-page-btn text-center mt-60">
                            <a href="package.html" class="button-fill-round">View All Offer</a>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-offer-tab3" role="tabpanel" aria-labelledby="pills-offer3">
                        <div class="row d-flex justify-content-center g-4">
                            {% for packages in hajj_packages %}
                            <div class="col-lg-4 col-md-6 col-6 fadeffect">
                                <div class="package-card-beta">
                                    <div class="package-thumb">
                                        <a href="{% url 'web:package_details' packages.id %}"><img
                                                src="{{packages.image_1.url}}" alt=""></a>
                                        <p class="card-lavel">
                                            <i class="bi bi-clock"></i> <span>{{packages.number_of_days}} Day & {{packages.number_of_nights}} night</span>
                                        </p>
                                    </div>
                                    <div class="package-card-body">
                                        <h3 class="p-card-title"><a href="{% url 'web:package_details' packages.id %}">{{packages.place_name}}</a></h3>
                                        <div class="p-card-bottom">
                                            <div class="book-btn">
                                                <a href="{% url 'web:package_details' packages.id %}">Book Now <i
                                                        class='bx bxs-right-arrow-alt'></i></a>
                                            </div>
                                            <div class="p-card-info">
                                                <span>From</span>
                                                <h6>₹{{packages.rate}} <span>Per Person</span></h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %} 
                        </div>
                        <div class="package-page-btn text-center mt-60">
                            <a href="package.html" class="button-fill-round">View All Offer</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/web/partials/header.html
{% load static %}

<body>




    <div class="mobile-search">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-11">
                    <label>What are you lookking for?</label>
                    <input type="text" placeholder="Search Products, Category, Brand">
                </div>
                <div class="col-1 d-flex justify-content-end align-items-center">
                    <div class="search-cross-btn">

                        <i class="bi bi-x"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="category-sidebar-wrapper">
        <div class="category-sidebar">
            <div class="category-header d-flex justify-content-between align-items-center">
                <h4>Category</h4>
                <div class="category-toggle">
                    <i class="bi bi-x-lg"></i>
                </div>
            </div>
            <div class="row row-cols-lg-3 row-cols-2 gy-5 mt-3">
                <div class="col">
                    <a class="category-box" href="package.html">
                        <div class="cate-icon mx-auto">
                            <img src="{% static 'web/images/icons/cate1.svg' %}" alt="">
                        </div>
                        <h5>Adventure</h5>
                    </a>
                </div>
                <div class="col">
                    <a class="category-box" href="package.html">
                        <div class="cate-icon mx-auto">
                            <img src="{% static 'web/images/icons/cate2.svg' %}" alt="">
                        </div>
                        <h5>Group Tour</h5>
                    </a>
                </div>
                <div class="col">
                    <a class="category-box" href="package.html">
                        <div class="cate-icon mx-auto">
                            <img src="{% static 'web/images/icons/cate3.svg' %}" alt="">
                        </div>
                        <h5>Couple Tour</h5>
                    </a>
                </div>
                <div class="col">
                    <a class="category-box" href="package.html">
                        <div class="cate-icon mx-auto">
                            <img src="{% static 'web/images/icons/cate4.svg' %}" alt="">
                        </div>
                        <h5>Single Tour</h5>
                    </a>
                </div>
                <div class="col">
                    <a class="category-box" href="package.html">
                        <div class="cate-icon mx-auto">
                            <img src="{% static 'web/images/icons/cate5.svg' %}" alt="">
                        </div>
                        <h5>Honeymoon</h5>
                    </a>
                </div>
                <div class="col">
                    <a class="category-box" href="package.html">
                        <div class="cate-icon mx-auto">
                            <img src="{% static 'web/images/icons/cate6.svg' %}" alt="">
                        </div>
                        <h5>Sea Beach</h5>
                    </a>
                </div>
                <div class="col">
                    <a class="category-box" href="package.html">
                        <div class="cate-icon mx-auto">
                            <img src="{% static 'web/images/icons/cate7.svg' %}" alt="">
                        </div>
                        <h5>Mountain Tour</h5>
                    </a>
                </div>
            </div>
        </div>
    </div>


    <header>
        <div class="header-area header-style-three position-absolute w-100">
            <div class="container-fluid">
                <div class="row">
                    <div
                        class="col-xxl-2 col-xl-2 col-lg-12 col-md-12 col-sm-12 col-xs-12 align-items-center d-xl-flex d-lg-block">
                        <div class="nav-logo d-flex justify-content-between align-items-center">
                            <a href="index.html"><img src="{% static 'web/images/logo-w.png' %}" alt="logo"></a>
                            <div class="mobile-menu d-flex ">
                                <div class="d-flex align-items-center">
                                    <div class="nav-right-icons d-xl-none d-flex align-items-center ">
                                        <div class="user-dropdown">
                                            <i class='bx bx-user-circle'></i>
                                            <ul class="user-drop-list">
                                                <li><a href="#">My Account</a></li>
                                                <li><a href="#">Login</a></li>
                                                <li><a href="#">Registration</a></li>
                                                <li><a href="#">Setting</a></li>
                                            </ul>
                                        </div>
                                        <div class="category-toggle"><i class='bx bx-category'></i></div>
                                    </div>
                                    <a href="javascript:void(0)" class="hamburger d-block d-xl-none">
                                        <span class="h-top"></span>
                                        <span class="h-middle"></span>
                                        <span class="h-bottom"></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xxl-7 col-xl-8 col-lg-9 col-md-8 col-sm-6 col-xs-6">
                        <nav class="main-nav">
                            <div class="inner-logo d-xl-none text-center">
                                <a href="#"><img src="{% static 'web/images/logo.png' %}" alt=""></a>
                            </div>
                            <ul>
                                <li class="">
                                    <a href="{% url 'web:index' %}">Home</a>
                                </li>
                                <li><a href="{% url 'web:about' %}">About Us</a></li>
                                <li class="">
                                    <a href="{% url 'web:services' %}">Services</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'web:packages' %}">Packages</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'web:blog' %}">Blogs</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'web:gallery' %}">Gallery</a>
                                </li>
                                <li><a href="{% url 'web:contact' %}">Contact Us</a></li>
                            </ul>
                            <div class="inner-contact-options d-xl-none">
                                <div class="contact-box-inner"><i class="bi bi-telephone-fill"></i> <a
                                        href="tel:+17632275032">+1 763-227-5032</a></div>
                                <div class="contact-box-inner"><i class="bi bi-envelope-fill"></i> <a
                                        href="https://demo.egenslab.com/cdn-cgi/l/email-protection#3851565e57785d40595548545d165b5755"><span
                                            class="__cf_email__"
                                            data-cfemail="92fbfcf4fdd2f7eaf3ffe2fef7bcf1fdff">[email&#160;protected]</span></a>
                                </div>
                            </div>
                        </nav>
                    </div>
                    <div class="col-xxl-3 col-xl-2 col-lg-1">
                        <div class="nav-right d-xl-flex d-none">
                            <div class="nav-right-hotline d-xxl-flex d-none">
                                <div class="hotline-icon">
                                    <img src="{% static 'web/images/icons/header-phone.svg' %}" alt="">
                                </div>
                                <div class="hotline-info">
                                    <span>Hot Line Number</span>
                                    <h6><a href="tel:8801761111456">+880 176 1111 456</a></h6>
                                </div>
                            </div>
                            <div class="nav-right-icons gap-3">
                                <div class="header-search search-btn">
                                    <i class='bx bx-search-alt'></i>
                                </div>
                                <div class="category-toggle"><i class='bx bx-category'></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

templates/web/services.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}


<div class="breadcrumb breadcrumb-style-one">
    <div class="container">
        <div class="col-lg-12 text-center">
            <h2 class="breadcrumb-title">Services</h2>
            <ul class="d-flex justify-content-center breadcrumb-items">
                <li class="breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                <li class="breadcrumb-item active">Services</li>
            </ul>
        </div>
    </div>
</div>

<div class="destination-wrapper pt-110">
    <div class="container">
        <div class="row g-3">
            {% for service in services %}
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="destination-card-style-two">
                    <div class="d-card-thumb">
                        <img src="{{service.service_image.url}}" alt="">
                    </div>
                    <div class="d-card-content">
                        <h4 class="destination-title"><a href="{% url 'web:service_details' service.id %}">{{service.service_name}}</a></h4>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}